package pl.marceligrabowski.githubtask.external.error.exception

class ExternalServiceInternalErrorException : RuntimeException("External service returned internal server error") {
}