package pl.marceligrabowski.githubtask.external.error.exception

class UserNotFoundException : RuntimeException("User not found") {
}